// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVNkPY8Y19NjVBKXYvdFsesRjVkuBQfWc',
    appId: '1:565465882481:android:9e65deec3efff445dee0d0',
    messagingSenderId: '565465882481',
    projectId: 'location-tracker-dev1',
    storageBucket: 'location-tracker-dev1.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpRkMbE5mg337aRWZap4la7kgkPk5ybCI',
    appId: '1:565465882481:web:cdf9e74544de3bb6dee0d0',
    messagingSenderId: '565465882481',
    projectId: 'location-tracker-dev1',
    authDomain: 'location-tracker-dev1.firebaseapp.com',
    storageBucket: 'location-tracker-dev1.appspot.com',
    measurementId: 'G-ERYMK2DJ3M',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPAcl9HBbRdojG572tooIoXM7qqVcvcbQ',
    appId: '1:565465882481:ios:330055c92221974fdee0d0',
    messagingSenderId: '565465882481',
    projectId: 'location-tracker-dev1',
    storageBucket: 'location-tracker-dev1.appspot.com',
    iosBundleId: 'com.example.locationTracker',
  );

}