// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2tGM9qfLHxNhg6yQFxTiHiLe0acCO_GM',
    appId: '1:152288671951:web:e4d1242567ffa7bc9ddfba',
    messagingSenderId: '152288671951',
    projectId: 'location-tracker-prod',
    authDomain: 'location-tracker-prod.firebaseapp.com',
    storageBucket: 'location-tracker-prod.appspot.com',
    measurementId: 'G-GL35KC1JTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5hWQq_Je0DkjkhP4LrLkB4eUf_tASZuw',
    appId: '1:152288671951:android:228c70287c6af3969ddfba',
    messagingSenderId: '152288671951',
    projectId: 'location-tracker-prod',
    storageBucket: 'location-tracker-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn5qlQvY1RPriraUqH9g3XrZ4ya3bDqtE',
    appId: '1:152288671951:ios:044f634d5f7a72a99ddfba',
    messagingSenderId: '152288671951',
    projectId: 'location-tracker-prod',
    storageBucket: 'location-tracker-prod.appspot.com',
    iosBundleId: 'com.example.locationTracker',
  );

}